CC = gcc
CFLAGS = -IC:/msys64/mingw64/include -Wall -Werror
LDFLAGS = -LC:/msys64/mingw64/lib
LIBS = -lraylib -lopengl32 -lgdi32 -lwinmm

SOURCES = botManager.c board.c notations.c movegen.c zobrist.c
TARGET = botManager.exe

$(TARGET): $(SOURCES)
	$(CC) $(SOURCES) -o $(TARGET) $(CFLAGS) $(LDFLAGS) $(LIBS)

clean:
	del $(TARGET)
